display error message on login screen
CodeForPoznan/pah-fm pull request #554
Opened 2020-09-16 18:27 UTC by juliaanholcer

403 status is sent by backend when the user does not exist or when the user doesn't belong to any group. In this case, different login error is displayed. I've also changed the alert to dismissable.

2020-09-17 20:34 UTC, pniedzwiedzinski requested changes

2020-09-17 20:34 UTC, pniedzwiedzinski commented on frontend/src/store/actions.js
> +      commit(mutations.SET_LOGIN_ERROR, status === 403 ? i18n.tc('login.login_group_error') : i18n.tc('login.login_error'));
`403` also means wrong login/password

I found that's also problem on backend - in response details it has the warning about groups (Even if user does not exist!)

2020-09-17 20:42 UTC, pniedzwiedzinski commented on frontend/src/store/actions.js
> +      commit(mutations.SET_LOGIN_ERROR, status === 403 ? i18n.tc('login.login_group_error') : i18n.tc('login.login_error'));
Please check if you have the same error, we might need to create a ticket about it

2023-03-25 22:06 UTC, arturtamborski commented
I think we can just freeze the frontend (vuejs) at this point and leave it untouched until react is ready.

2023-03-25 22:06 UTC, closed without merging